export const color ={
    backgroundColor:"#050507",
    inputFieldColor:'#171717',
    buttonColor:'#373739',
    placeholderColor:'#555C73',
    onBoardingButton:'#0082FB',
    whiteFontColor:'#FFFFFF',
    privacyPolicyColor:'#54B2E7',
    whiteColor:'#FFFFFF',
    balckFontColor:'#050507',
    modalDescriptionText:'#D9D9D9',
    whiteWithfiftypercentOpacity:'#ffffff80',
    WhiteWithThirtypercentOpacity:'#ffffff33',
    shareButtonColor:'#232121',
    whiteWithFifteenPercentOpacity:'#ffffff26',
    whitewithThirty:'#ffffff4D',
};